### ISSUE TITLE
Espanol Translation

### ISSUE THREAD

**Issue by jhamlet** [jhamlet/ffg-sw-char-acro#13]
@erahard The first version of [Aurebesh Gray in Español](https://github.com/jhamlet/ffg-sw-char-acro/blob/aurebesh-es/pub/es/aurebesh-eote-g.pdf) is available.

Please review, and let me know if I messed anything up.

Thanks,

;-j

**Comment by erahard** [comment]
Hi there,

The sheet looks awesome! At first glance I have only found a small typo,
that is the skill ¨core worlds¨ translates into spanish as ¨Mundos del
Núcleo¨ not ¨Mundose del Núcleo¨so ther is an esxtra ¨e¨.

Aside from that everthing looks great.

Best regards.

2015-10-07 15:19 GMT+02:00 Jerry Hamlet notifications@github.com:

**Comment by erahard** [comment]
Hi Jerry,

I am wondering if you have managed to find the time to solve the small typo
I told you about in my last email. However I do not want to put pressure on
you.

Best regards.

2015-10-09 9:38 GMT+02:00 Erahard E erahard2@gmail.com:

**Comment by jhamlet** [comment]
Erahard,

Again, apologies for the delay. I have a ton of excuses, but I really apologize.

I made the typo/miss-spelling corrections [aurebesh-eote-g.pdf](https://github.com/jhamlet/ffg-sw-char-acro/blob/aurebesh-es/pub/es/aurebesh-eote-g.pdf)

If it looks good, I'll start doing the other templates. (This is labor intensive, so it **will** take a bit of time.)

;-j

**Comment by erahard** [comment]
Looks great! However, before you start working on the other templates I
would like to submit it to the communtiy of spanish gamers so that they can
make suggestions. Once they made some comments you can do a final version.
Do I have your permission to submit it to player communities?

Best regards.

2015-10-29 19:11 GMT+01:00 Jerry Hamlet notifications@github.com:

**Comment by jhamlet** [comment]
@erahard : I do not have a problem with you reviewing it with your fellow gamers.

I am happy to make any **textual/spelling** changes, however, I do not want to make any **layout** changes though.

(FWIW: I'm working on another project which will make this one obsolete, so I do not want to invest a lot of time in it.)

**Comment by erahard** [comment]
Hi Jerry,

After a few days being reviewed by players here there are the some typos:
- Survival skill: Should be ¨Supervivencia¨and not Su_r_pervivencia¨. There
  is an extra r.
- Obligation/duty: Should be Obligación/Deber instead of Obligación/Deber
  _es_.
- Encumbrance: Should be ¨Impedimento¨ instead of ¨Impediment_a_¨

I think that's everything that needs modification. Hope not to be
disturbing you too much.

Best regards.

2015-10-30 23:18 GMT+01:00 Jerry Hamlet notifications@github.com:

**Comment by jhamlet** [comment]
Ok. I've updated the strings file.

It might take me a day, or two, to generate a new pdf (I'm away for a business conference).

Bug me if you do not hear anything by Monday, November 9.

**Comment by jhamlet** [comment]
@erahard: Updated [aurebesh-eote-g.pdf](https://github.com/jhamlet/ffg-sw-char-acro/blob/aurebesh-es/pub/es/aurebesh-eote-g.pdf)

Double-check that I got all of the above, and then I can start working on the other versions.

**Comment by erahard** [comment]
Everything checks out and it looks awesome! Thanks for the hard work and do
not be in a hurry to make the other sheet versions as I know it takes some
effort.

Best regards.

2015-11-05 5:22 GMT+01:00 Jerry Hamlet notifications@github.com:
